---
- name: Install fisherman
  shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

- name: 
  command: /usr/local/bin/fish -c "fisher install '{{item.name}}'"
  with_items: '{{ fisher_packages }}'