---
- name: Install fisherman
  shell: curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

- name: Install by fisher
  shell: fish -c "fisher {{ item }}"
  with_items: '{{ fisher_packages }}'