---
- name: Create fish functions directory
  file:
    path: ~/.config/fish/functions
    state: directory

- name: Install fisher
  get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: ~/.config/fish/functions/fisher.fish

- name: Install fisher plugins
  command: /opt/homebrew/bin/fish -c "fisher install '{{ item.name }}'"
  with_items: '{{ fisher_packages }}'
