---
osx_defaults:
  # Global
  - domain: NSGlobalDomain
    key: NSCloseAlwaysConfirmsChanges
    type: bool
    value: true

  - domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false

  - domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: bool
    value: true

  - domain: NSGlobalDomain
    key: com.apple.trackpad.forceClick
    type: bool
    value: false

  - domain: NSGlobalDomain
    key: com.apple.sound.uiaudio.enabled
    type: bool
    value: false

  # Dock
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true

  - domain: com.apple.dock
    key: orientation
    type: string
    value: "bottom"

  - domain: com.apple.dock
    key: mineffect
    type: string
    value: "scale"

  - domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

  - domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: 14

  # Finder
  - domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

  - domain: com.apple.finder
    key: FXShowPosixPathInTitle
    type: bool
    value: true

  - domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "Nlsv"

  - domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true

  - domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true

  - domain: com.apple.finder
    key: ShowTabView
    type: bool
    value: true

  # Screenshot
  - domain: com.apple.screencapture
    key: name
    type: string
    value: "ss"

  - domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ ansible_facts.env.HOME }}/Pictures/ss"
