---
- name: Create screenshot directory
  file:
    path: "{{ ansible_facts.env.HOME }}/Pictures/ss"
    state: directory

- name: Disable Spotlight shortcut (Cmd+Space)
  command: >
    /usr/libexec/PlistBuddy -c
    "Set :AppleSymbolicHotKeys:64:enabled false"
    {{ ansible_facts.env.HOME }}/Library/Preferences/com.apple.symbolichotkeys.plist
  changed_when: false

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ osx_defaults }}"

- name: Restart Dock
  command: killall Dock
