---
- name: Create screenshot directory
  file:
    path: "{{ ansible_env.HOME }}/screenshot"
    state: directory

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ osx_defaults }}"

- name: Restart Dock
  command: killall Dock
