---
- name: Ensure git clone parent directories exist
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
  with_items:
    - "{{ git_repositories }}"

- name: Clone git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    accept_hostkey: yes
  with_items:
    - "{{ git_repositories }}"
  failed_when: no