---
- name: Setup pnpm global bin directory
  command: pnpm setup
  environment:
    PATH: "{{ ansible_facts.env.HOME }}/.local/share/mise/shims:{{ ansible_facts.env.HOME }}/.local/bin:/opt/homebrew/bin:{{ ansible_facts.env.PATH }}"
    PNPM_HOME: "{{ ansible_facts.env.HOME }}/.local/share/pnpm"
  changed_when: false

- name: Install pnpm global packages
  command: "pnpm install -g {{ item.name }}"
  environment:
    PATH: "{{ ansible_facts.env.HOME }}/.local/share/pnpm:{{ ansible_facts.env.HOME }}/.local/share/mise/shims:{{ ansible_facts.env.HOME }}/.local/bin:/opt/homebrew/bin:{{ ansible_facts.env.PATH }}"
    PNPM_HOME: "{{ ansible_facts.env.HOME }}/.local/share/pnpm"
  with_items: "{{ pnpm_global_packages }}"
