---
homebrew_packages:
  - { name: readline }
  - { name: openssl }
  - { name: coreutils }
  - { name: ansible }
  - { name: git }
  - { name: git-secrets}
  - { name: ghq }
  - { name: gh }
  - { name: curl }
  - { name: tree }
  - { name: jq }
  - { name: direnv }
  - { name: mise }
  - { name: uv }
  - { name: tflint }
  - { name: tmux }
  - { name: grep }
  - { name: fish }
  - { name: starship }
  - { name: fzf }
  - { name: trash }

homebrew_cask_packages:
  - { name: 1password-cli }
  - { name: clipy }
  - { name: drawio }
  - { name: google-chrome }
  - { name: google-japanese-ime }
  - { name: iterm2 }
  - { name: karabiner-elements }
  - { name: obsidian }
  - { name: rancher }
  - { name: qlmarkdown }
  - { name: rectangle }
  - { name: typora }
  - { name: alfred }
  - { name: visual-studio-code }
